Disable heater
KalicoCrew/kalico pull request #425
Opened 2024-11-04 23:36 UTC by Zeanon

Fixes https://github.com/DangerKlippers/danger-klipper/issues/424

## Checklist

- [ ] pr title makes sense
- [ ] squashed to 1 commit
- [ ] added a test case if possible
- [ ] if new feature, added to the readme
- [ ] ci is happy and green

2024-11-22 11:22 UTC, rogerlz requested changes

2024-11-22 11:22 UTC, rogerlz commented on klippy/extras/adxl345.py
> +            )
I would prefer it to be a heater feature so it is generic enough for any mcu.

2024-11-23 22:10 UTC, The-Original-Reth commented on klippy/extras/adxl345.py
> +            )
To comment on this, I think it might be better to add as an optional thing to do rather than automatically disable the heaters.

2024-11-25 21:45 UTC, Zeanon commented on klippy/extras/adxl345.py
> +            )
it was always optional

but I now moved it to heater

2024-12-10 20:15 UTC, rogerlz requested changes

2024-12-10 20:15 UTC, rogerlz commented on README.md
> +- [adxl: disable heaters when connected](https://github.com/DangerKlippers/danger-klipper/pull/425)
the message needs improving

2024-12-10 20:15 UTC, rogerlz commented on docs/Config_Reference.md
> +#   List of mcus that should disable the heater if connected, usefull for nozzle adxls
typo in useful

2024-12-10 20:15 UTC, rogerlz commented on klippy/extras/heaters.py
> +        if hasattr(config, "getlist"):
why the hasattr()?

2024-12-10 20:17 UTC, Zeanon commented on klippy/extras/heaters.py
> +        if hasattr(config, "getlist"):
Cause some dummy configs don't have that attribute and I ran into issues without it

2024-12-10 20:17 UTC, Zeanon commented on docs/Config_Reference.md
> +#   List of mcus that should disable the heater if connected, usefull for nozzle adxls
Whoops

2025-03-25 18:36 UTC, rogerlz commented
After months of thought and consideration, I believe this feature doesn't bring enough value. Issue #424 was a human error, very unlikely to affect someone twice, and it's improbable that anyone would enable this parameter before encountering the issue firsthand.

2025-03-25 18:36 UTC, closed without merging