temperature_fan: Improved code quality of fan curve and fixed hysteresis
KalicoCrew/kalico pull request #466
Opened 2024-12-06 13:14 UTC by NokkOnEffect

This pull request contains improvements to the code quality of the `ControlCurve` class to improve readability. Furthermore unnecessary operations were removed.
The current behaviour of the hysteresis when using a fan curve for control is incorrect and causes intermittent jumps between fixed pwm values without following the curve or reaching either end of the curve. This pull request contains an improved implementation.

Please be aware that this requests testing is limited as I'm currently not able to validate the behaviour in a live environment! I am open to feedback.

## Checklist

- [x] pr title makes sense
- [x] squashed to 1 commit
- [x] ~~added a test case if possible~~
- [x] if new feature, added to the readme
- [x] ci is happy and green

2024-12-10 20:05 UTC, rogerlz commented on klippy/extras/temperature_fan.py
> -        self.smooth_readings = config.getint("smooth_readings", 10, minval=1)
this should be deprecated first to not break people running it
I also see no changes to the documentation about this change

2024-12-11 18:41 UTC, Zeanon requested changes

2024-12-11 18:41 UTC, Zeanon commented on klippy/extras/temperature_fan.py
> +        current_speed = self.controlled_fan.last_speed_value
dont use `controlled_fan.last_speed_value` but `temperature_fan.last_speed_value`

2024-12-13 22:18 UTC, Zeanon approved these changes

2024-12-23 01:35 UTC, rogerlz approved these changes

2024-12-23 01:36 UTC, merged