driver_cs has been added to tmc5160
KalicoCrew/kalico pull request #491
Opened 2024-12-17 19:09 UTC by HonestBrothers

Previously, CS (current scaler) has been automatically set to 31. The only time CS would only change was to adjust the holding_current. However, some users found certain motor, driver, and voltage combinations to produce less than ideal results on tmc5160 drivers. Noise, VFA's and overheating were a common occurrence, particularly on high amp drivers and high power motors. 

According to the excel spreadsheet provided by Trinamic to tune the 5160 drivers, the CS value should be set so that Rsense on the spreadsheet matches the 'sense_resistor' value as defined in printer.cfg. By adjusting the CS value so that these two match, we can define much more adequate hysteresis values.  This means that high power motors can now be run at high voltage (>48V) and their current may be run at RMS value without overheating.

https://www.analog.com/media/en/engineering-tools/design-tools/tmc5160_calculations.xlsx

2025-01-06 14:13 UTC, CarVac commented
What are those `.idea` files?

2025-01-06 14:23 UTC, HonestBrothers commented
> What are those `.idea` files? I think they need to be removed.

PyCharm bloat. I'll remove them. 

> 
> Also, the config_changes needs tweaking. CS doesn't necessarily have to be set based on current as calculated by TMC5160_calcs, it can be that value or higher (since globalscaler is still available to reduce the run current.

Correct, working on an error if it's lower to where the target current can't be reached.

2025-01-06 14:38 UTC, HonestBrothers commented
I also made an update to 2130
I implemented math.ceil for cs here:
```
       cs = (math.ceil(
            int(32.0 * sense_resistor * current * math.sqrt(2.0) / vref)
            - 1
        ))
```

instead of the default behavior where 0.5 gets added to vref:
```
            cs = (
                int(32.0 * sense_resistor * current * math.sqrt(2.0) / vref + 0.5)
                - 1
            )
```

I'm not sure why 0.5 was being added other than rounding. It's not in the datasheets.

2025-01-06 21:01 UTC, CarVac commented
Make sure to fix the "xlxs" typo in the GLOBALSCALER_ERROR (line 265 in tmc5160.py)

2025-01-08 19:53 UTC, agravelot commented
related to https://github.com/Klipper3d/klipper/pull/6644

2025-01-17 18:34 UTC, Zeanon requested changes

2025-01-17 18:34 UTC, Zeanon commented on klippy/extras/tmc5160.py
> +        self.sense_resistor = float(config.get("sense_resistor", None))
No reason to define that, its already defined via the super class

2025-01-17 18:34 UTC, Zeanon commented on klippy/extras/tmc5160.py
> +            math.ceil(
I know we talked about that but I realized that those might actually not be equivalent, might be good to get some insight from @rogerlz and @dalegaard here (int cas with +0.5 vs math.ceil)

2025-01-17 18:34 UTC, Zeanon commented on klippy/extras/tmc5160.py
> +        ihold = int(min((hold_current / run_current) * irun, irun))
on one hand this looks right, on the other hand I would just calculate ihold like before if it is applied (on the other hand, maybe make ihold adjustable in the process as well?)
also need some feedback from @rogerlz and @dalegaard I think

2025-01-19 04:47 UTC, HonestBrothers commented on klippy/extras/tmc5160.py
> +            math.ceil(
This is hold over from mainline code, I'm just not sure why it's there. It doesn't match the datasheets.

2025-01-19 04:50 UTC, HonestBrothers commented on klippy/extras/tmc5160.py
> +        ihold = int(min((hold_current / run_current) * irun, irun))
This is give or take how Marlin does it. I'm a fan because it's simple.

2025-01-19 10:24 UTC, Zeanon commented on klippy/extras/tmc5160.py
> +        ihold = int(min((hold_current / run_current) * irun, irun))
Fair point

2025-01-20 03:29 UTC, closed without merging

2025-01-20 03:35 UTC, rogerlz commented
Unfortunately this PR was targeting the master branch that should not exist. The PR got automatically closed as I deleted master and it has to be submitted again pointing to the correct branch.