Expose slope_control field on TMC2240.
KalicoCrew/kalico pull request #510
Opened 2024-12-28 06:33 UTC by liampwll

The chip has a default value of 0, corresponding to 100V/µs. The default is overridden with 2 here, corresponding to 400V/µs to approximately match the TMC2209. This should also solve some overheating issues as it lowers the power dissipation at a 50kHz chopper frequency by around 1W.

This is currently untested.

## Checklist

- [x] pr title makes sense
- [x] squashed to 1 commit
- [ ] ~~added a test case if possible~~
- [ ] ~~if new feature, added to the readme~~
- [x] ci is happy and green

2025-01-03 04:21 UTC, liampwll commented
Comments on the Klipper PR indicate that this does indeed have a significant impact on stepsticks.

2025-01-13 11:35 UTC, rogerlz requested changes

2025-01-13 11:35 UTC, rogerlz commented on klippy/extras/tmc2240.py
> +        set_config_field(config, "slope_control", 2)
Thanks for working on this. I would prefer not to change that default without enough feedback.
I agree that a message would help, and I believe that a sentence next to the parameter in the Config Reference is enough.

2025-01-13 11:45 UTC, liampwll commented on klippy/extras/tmc2240.py
> +        set_config_field(config, "slope_control", 2)
Also moved the parameter up a bit in the config reference to distinguish the new comment from the existing one.

2025-01-17 20:11 UTC, rogerlz approved these changes

2025-01-17 20:11 UTC, merged