added mixing extruder support from stale klipper pull request
KalicoCrew/kalico pull request #512
Opened 2024-12-30 01:32 UTC by JulianStremel

I am currently working on a 4 in 1 out mixing hotend printer and needed support for that kind of setup.
So after looking at klipper i saw the [stale pull request ](https://github.com/Klipper3d/klipper/pull/5960/commits/38710c4491639628db5e61fa052b5cb0a4612731)just brought it over here.

_Enter a good description of whats being changed and WHY

## Checklist

- [x] pr title makes sense
- [x] squashed to 1 commit
- [x] added a test case if possible
- [x] if new feature, added to the readme
- [ ] ci is happy and green

2025-01-02 09:50 UTC, rogerlz requested changes
thanks for working on this.. there is a few changes needed and the CI must pass

2025-01-02 09:50 UTC, rogerlz commented on docs/G-Codes.md
> +[mixingextruder config section](Config_Reference.md#mixingextruder) is
the reference is wrong

2025-01-02 09:50 UTC, rogerlz commented on klippy/kinematics/extruder.py
> +        return rotation_dist
these methods are doing nothing but calling themselves recursively

2025-01-02 15:09 UTC, JulianStremel commented
ci is passing after removing gradient mixing feature.
I currently do not have my printer up and running but i will have a look into the gradient once i have functional hardware to test on.

2025-01-02 15:10 UTC, JulianStremel commented on docs/G-Codes.md
> +[mixingextruder config section](Config_Reference.md#mixingextruder) is
Fixed thanks for the fast reply.

2025-01-07 22:12 UTC, rogerlz commented
@JulianStremel I fixed what was missing in the gradient code and formatted the files. Please test?

2025-01-13 11:31 UTC, rogerlz approved these changes

2025-01-13 11:32 UTC, merged